### ISSUE TITLE
Image broken with FileSystem media source

### ISSUE THREAD

**Issue by matdave** [donShakespeare/Structures#1]
Using the FileSystem media source (default) the image breaks on insertion
http://recordit.co/ldCm7nuuRI

**Comment by donShakespeare** [comment]
Slip of my keyboard.
In your `st.tinymce_config` chunk, change:

`document_base_url: MODx.config.site_url+"assets/",`
to
`document_base_url: MODx.config.site_url,`

See https://github.com/donShakespeare/Structures/commit/f7f9e3b27d5798cee7644281fc934821b57df5de#diff-152772aabe222d71fb4e0ee4e0d6a5caL169
